name: Build & Push Docker Image

on:
  workflow_dispatch:
  push:
    branches:
      - "main"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Login to Hogbisz Container Registry
        uses: docker/login-action@v2
        with:
          registry: https://registry.hogbisz.com
          username: github
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.RH_DOCKERHUB_USERNAME }}
          password: ${{ secrets.RH_DOCKERHUB_TOKEN }}
      - name: Build for armv7 and push-
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.test
          platforms: linux/amd64
          push: true
          tags: |
            registry.hogbisz.com/rust-armv7-builder:test
            ghcr.io/reman-hogbisz/rust-armv7-builder:test
            remanhogbisz/rust-armv7-builder:test